#!/bin/sh


while read line; do
    echo ${#line}
    if [ ${#line} -ge 50 ]; then
        echo "Zbyt dluga nazwa commita - maksymalna dlugosc to 50 znakow."
        echo "Ta nazwa miala ${#line} znakow."
        echo "${line}"
        exit 1
    fi;
done < "${1}"

exit 0
